version: '3.8'

services:
  mysql:
    image: mysql:8
    container_name: expense_mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: expense_tracker
      MYSQL_USER: expense_user
      MYSQL_PASSWORD: password123
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - expense_network
    restart: unless-stopped

  mongo:
    image: mongo:6
    container_name: expense_mongo
    environment:
      MONGO_INITDB_DATABASE: expenses
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - expense_network
    restart: unless-stopped

  backend:
    build: 
      context: ./backend
      target: development
    container_name: expense_backend
    environment:
      FLASK_ENV: development
      SECRET_KEY: dev-secret-key-12345
      MYSQL_HOST: mysql
      MYSQL_DATABASE: expense_tracker
      MYSQL_USER: expense_user
      MYSQL_PASSWORD: password123
      MONGO_HOST: mongo
      MONGO_DATABASE: expenses
    ports:
      - "5000:5000"
    depends_on:
      - mysql
      - mongo
    volumes:
      - ./backend:/app
    networks:
      - expense_network
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      target: development
    container_name: expense_frontend
    environment:
      REACT_APP_API_URL: http://localhost:5000
    ports:
      - "3000:3000"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - expense_network
    restart: unless-stopped

volumes:
  mysql_data:
  mongo_data:

networks:
  expense_network:
    driver: bridge

