services:
  # Flask Backend
  - type: web
    name: expense-tracker-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
      - key: FLASK_ENV
        value: production

  # React Frontend
  - type: web
    name: expense-tracker-frontend
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_VERSION
        value: 18
    staticPublishPath: build
    routes:
      - type: rewrite
        source: /api/*
        destination: https://expense-tracker-backend.onrender.com/api/$1
