services:
  - type: web
    name: ai-expense-tracker-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT backend.app:app
    envVars:
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        generateValue: true
      - key: JWT_SECRET_KEY
        generateValue: true
      - key: PYTHONPATH
        value: .

  - type: static
    name: ai-expense-tracker-frontend
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: ./frontend/build
